// Shared types for the Harborlight parent digest. The data files that back these
// live in `data/harborlight/*.json` and are regenerated by the digest pipeline.

export type DigestCategory =
  | "childrens_house_weekly"
  | "it_weekly"
  | "school_wide"
  | "classroom";

export type Confidence = "confirmed" | "partial";

export interface KeyDate {
  date: string; // YYYY-MM-DD
  label: string;
}

export interface DigestLink {
  label: string;
  url: string;
}

export interface DigestItem {
  id: string;
  category: DigestCategory;
  categoryLabel: string;
  classroom: string | null;
  title: string;
  date: string; // YYYY-MM-DD
  summary: string;
  keyDates: KeyDate[];
  actionItems: string[];
  links: DigestLink[];
  confidence: Confidence;
  source: string;
}

export interface UpcomingEvent {
  date: string; // YYYY-MM-DD
  label: string;
  category: DigestCategory;
  source: string;
}

// A stable label + accent token per category, reused by the page and the feed.
export const CATEGORY_META: Record<
  DigestCategory,
  { label: string; short: string }
> = {
  childrens_house_weekly: { label: "Notes from Marcy", short: "Children's House" },
  it_weekly: { label: "Notes from Dorah", short: "Infant / Toddler" },
  school_wide: { label: "School-wide", short: "School-wide" },
  classroom: { label: "Classroom", short: "Classroom" },
};
