/**
 * Thin wrapper over the gtag call already installed in app/layout.tsx.
 *
 * Event names and parameters are a fixed vocabulary on purpose. GA4 does not rewrite
 * history when you rename something: the old name keeps its data and the new one starts
 * empty, so a rename silently splits a trend line. Adding a value to a union here is
 * cheap; changing one that has shipped is not.
 */

declare global {
  interface Window {
    gtag?: (command: string, ...args: unknown[]) => void;
  }
}

/** Which piece of the site an event came from. Registered in GA4 as a custom dimension. */
export type Surface =
  | "digest"
  | "digest-archive"
  | "beverly-hub"
  | "find-the-money"
  | "property-tax"
  | "what-sets-your-taxes"
  | "budget-explainer"
  | "fy27-budget"
  | "development-map"
  | "who-beverly-is";

export type TrackEvent =
  /** A primary source was opened: a timestamped recording, a filed ordinance, minutes. */
  | "source_opened"
  /** Background reading, deliberately separate from source_opened. */
  | "read_more_clicked"
  /** An "add to calendar" control was used. */
  | "calendar_added"
  /** A section scrolled into view. Once per section per page load. */
  | "read_depth"
  /** A control inside an interactive piece was touched. Once per control per page load. */
  | "tool_used"
  /** An interactive piece reached a meaningful end state. */
  | "tool_outcome";

type Params = Record<string, string | number | boolean>;

/**
 * No-ops when gtag is unavailable, which covers server rendering, local dev without a
 * GA id, and every reader running a content blocker. Analytics must never be able to
 * break a page whose whole point is being readable.
 */
export function track(event: TrackEvent, params: Params = {}): void {
  if (typeof window === "undefined" || typeof window.gtag !== "function") return;
  try {
    window.gtag("event", event, params);
  } catch {
    /* ignore */
  }
}

/**
 * Fires an event at most once per page load for a given key. Without this, dragging a
 * year scrubber sends a few hundred tool_used events and the data becomes noise
 * generated by whoever happened to fidget.
 */
const seen = new Set<string>();

export function trackOnce(event: TrackEvent, key: string, params: Params = {}): void {
  const id = `${event}:${key}`;
  if (seen.has(id)) return;
  seen.add(id);
  track(event, params);
}
